#
#     Copyright (C) 2016  Mihály Szabó
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: 2
jobs:
  checkout_code:
    docker: &docker_image
      - image: circleci/openjdk
    working_directory: /home/circleci/libreplicator
    steps:
      - checkout
      - run:
          name: Generate checksums of build files
          command: sha1sum pom.xml **/pom.xml > sha1sums.txt
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - libreplicator
  check_license_headers:
    docker: *docker_image
    working_directory: /home/circleci/libreplicator
    steps:
      - attach_workspace: &attach_workspace
          at: /home/circleci
      - restore_cache: &restore_dependency_cache
          keys:
            - dependency_cache_{{ .Environment.CIRCLE_JOB }}_{{ checksum "sha1sums.txt" }}
      - run:
          name: Check license headers
          command: mvn license:check
      - save_cache: &save_dependency_cache
          key: dependency_cache_{{ .Environment.CIRCLE_JOB }}_{{ checksum "sha1sums.txt" }}
          paths:
            - /home/circleci/.m2
  check_code_style:
    docker: *docker_image
    working_directory: /home/circleci/libreplicator
    steps:
      - attach_workspace: *attach_workspace
      - restore_cache: *restore_dependency_cache
      - run:
          name: Check code style
          command: mvn antrun:run@detekt --non-recursive
      - save_cache: *save_dependency_cache
  run_tests:
    docker: *docker_image
    working_directory: /home/circleci/libreplicator
    steps:
      - attach_workspace: *attach_workspace
      - restore_cache: *restore_dependency_cache
      - run:
          name: Run tests
          command: mvn test
      - save_cache: *save_dependency_cache
workflows:
  version: 2
  check_and_test:
    jobs:
      - checkout_code
      - check_license_headers:
          requires:
            - checkout_code
      - check_code_style:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - checkout_code
